#cloud-config
users:
  - name: vmadmin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: user,admin
    homedir: /home/vmadmin
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'sml12345'     
# login ssh and console with password
ssh_pwauth: true
disable_root: false    
packages:
  - apache2 
  - curl 
  - wget
  - php
  - libapache2-mod-php
  - php-mysql
  - mariadb-server
  - unzip

write_files:
 - content: |
    CREATE USER 'vmadmin' IDENTIFIED BY 'sml12345';
    CREATE DATABASE IF NOT EXISTS nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    GRANT ALL PRIVILEGES ON nextcloud.* TO 'vmadmin';
    FLUSH PRIVILEGES;    
   path: /tmp/initdb.sql
   permissions: '0644' 
 - content: |
    <?php
    $AUTOCONFIG = array(
      "dbtype"        => "mysql",
      "dbname"        => "nextcloud",
      "dbuser"        => "vmadmin",
      "dbpass"        => "sml12345",
      "dbhost"        => "localhost",
      "dbtableprefix" => "",
      "adminlogin"    => "vmadmin",
      "adminpass"     => "sml12345",
      "directory"     => "/var/www/html/nextcloud/data",
    ); 
   path: /tmp/autoconfig.php
   permissions: '0644' 
runcmd:
  - 'sudo mysql </tmp/initdb.sql'
  - sudo sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mysql
  - sudo wget https://download.nextcloud.com/server/releases/nextcloud-24.0.3.zip
  - sudo unzip nextcloud-24.0.3.zip -d /var/www/html/
  - sudo chown -R www-data:www-data /var/www/html/
  - sudo apt install -y imagemagick php7.4-imagick libapache2-mod-php7.4 php7.4-common php7.4-mysql php7.4-fpm php7.4-gd php7.4-json php7.4-curl php7.4-zip php7.4-xml php7.4-mbstring php7.4-bz2 php7.4-intl php7.4-bcmath php7.4-gmp
  - sudo mv /tmp/autoconfig.php /var/www/html/nextcloud/config/autoconfig.php
  - sudo systemctl restart apache2